from django.db import models
from django.contrib.auth.models import User

class Show(models.Model):      
    
    advanced = models.BooleanField()
    ages = models.CharField(max_length=300)
    artist = models.CharField(max_length=100)
    billing = models.CharField(max_length=300)
    bus_call = models.TimeField()
    contracted = models.BooleanField()
    contract_signed = models.BooleanField()
    comments = models.CharField(max_length=500)
    curfew = models.TimeField()
    date = models.DateField() 
    date_on_calendar = models.BooleanField()
    date_on_venue_site = models.BooleanField()
    date_on_artist_site = models.BooleanField()
    date_on_socials = models.BooleanField()
    deposit = models.IntegerField()
    deposit_paid = models.BooleanField()
    door_price = models.IntegerField()
    door_time = models.TimeField()
    drive_time = models.CharField(max_length=300)
    gross_income = models.IntegerField()
    guarantee = models.IntegerField()
    guest_list = models.CharField(max_length=300)
    guest_list_sent = models.BooleanField()
    hotel = models.ForeignKey("Hotel", on_delete=models.CASCADE, null=True)
    load_in = models.TimeField()
    miles_to_drive = models.IntegerField()
    promo_materials_sent = models.BooleanField()
    promoter = models.ForeignKey("Promoter", on_delete=models.SET_NULL, null=True)
    public_private =  models.CharField(max_length=10)
    routing = models.CharField(max_length=300)
    routing_notes = models.CharField(max_length=500)
    runner = models.BooleanField()
    show_length = models.CharField(max_length=300)
    show_time = models.TimeField()
    sound_check = models.TimeField()
    support = models.CharField(max_length=300)
    status = models.CharField(max_length=300)
    terms = models.CharField(max_length=300)
    ticket_sales = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    venue = models.ForeignKey("Venue", on_delete=models.SET_NULL, null=True) 
    weather = models.CharField(max_length=50)