# Generated by Django 3.2.4 on 2021-06-14 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('confirmation', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('hall_fee', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('merch_sales', models.CharField(max_length=100)),
                ('merch_fee', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced', models.BooleanField()),
                ('ages', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=100)),
                ('billing', models.CharField(max_length=30)),
                ('bus_call', models.TimeField()),
                ('contracted', models.BooleanField()),
                ('contract_signed', models.BooleanField()),
                ('comments', models.CharField(max_length=500)),
                ('curfew', models.TimeField()),
                ('date', models.DateField()),
                ('date_on_calendar', models.BooleanField()),
                ('date_on_venue_site', models.BooleanField()),
                ('date_on_artist_site', models.BooleanField()),
                ('date_on_socials', models.BooleanField()),
                ('deposit', models.IntegerField()),
                ('deposit_paid', models.BooleanField()),
                ('door_price', models.IntegerField()),
                ('door_time', models.TimeField()),
                ('drive_time', models.CharField(max_length=30)),
                ('gross_income', models.IntegerField()),
                ('guarantee', models.IntegerField()),
                ('guest_list', models.CharField(max_length=300)),
                ('guest_list_sent', models.BooleanField()),
                ('load_in', models.TimeField()),
                ('miles_to_drive', models.IntegerField()),
                ('routing', models.CharField(max_length=300)),
                ('routing_notes', models.CharField(max_length=500)),
                ('runner', models.BooleanField()),
                ('show_length', models.CharField(max_length=30)),
                ('show_time', models.TimeField()),
                ('sound_check', models.TimeField()),
                ('support', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('terms', models.CharField(max_length=30)),
                ('ticket_sales', models.IntegerField()),
                ('weather', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmapi.hotel')),
                ('promoter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmapi.promoter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmapi.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmapi.show')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=20)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmapi.show')),
            ],
        ),
    ]
