# Generated by Django 3.2.4 on 2021-06-16 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='show',
            name='public_private',
            field=models.CharField(default='COMMENT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='contact',
            field=models.CharField(default='COMMENT', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='promoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmapi.promoter'),
        ),
        migrations.AlterField(
            model_name='show',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmapi.venue'),
        ),
    ]
