# Generated by Django 3.2.4 on 2021-06-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmapi', '0002_alter_show_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
