# Generated by Django 3.2.4 on 2021-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapi', '0003_venue_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='promo_materials_sent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promoter',
            name='comments',
            field=models.CharField(max_length=500),
        ),
    ]
