# Generated by Django 3.2.4 on 2021-06-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmapi', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmapi.hotel'),
        ),
        migrations.AlterField(
            model_name='show',
            name='promoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmapi.promoter'),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmapi.venue'),
        ),
    ]
